services:
  - type: web
    name: gaia-receipt
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn wsgi:app
    envVars:
      - key: GOOGLE_APPLICATION_CREDENTIALS
        sync: false 